<?xml version="1.0"?>
<robot name="arm" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- PROPERTY LIST -->
    <xacro:property name="link_1_length" value="0.08"/>
    <xacro:property name="link_1_radius" value="0.05"/>
    <xacro:property name="link_2_length" value="0.08"/>
    <xacro:property name="link_2_radius" value="0.05"/>
    <xacro:property name="link_3_length" value="0.08"/>
    <xacro:property name="link_3_radius" value="0.05"/>
    <!-- Defining the colors used in this robot -->
    <material name="green">
        <color rgba="0.5 1 0.5 1"/>
    </material>

    <!-- link models-->
    <xacro:macro name="arm_link" params="prefix link1_length link1_radius link2_length link2_radius">
	<joint name="arm_joint${prefix}" type="continuous">
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="arm_link${prefix-1}_3"/>
            <child link="arm_link${prefix}_1"/>
            <axis xyz="0 1 0"/>
        </joint>

	<link name="arm_link${prefix}_1">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
            	<geometry>
                    <sphere radius="${link2_radius}"/>
            	</geometry>
            	<material name="green" />
            </visual>
    	</link>
	
	<joint name="arm_joint${prefix}_2" type="fixed">
            <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
            <parent link="arm_link${prefix}_1"/>
            <child link="arm_link${prefix}_2"/>
        </joint>

	<link name="arm_link${prefix}_2">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
            	<geometry>
                    <cylinder length="${link2_length}" radius="${link2_radius}"/>
            	</geometry>
            	<material name="green" />
            </visual>
    	</link>

	<joint name="arm_joint${prefix}_3" type="fixed">
            <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
            <parent link="arm_link${prefix}_2"/>
            <child link="arm_link${prefix}_3"/>
        </joint>

	<link name="arm_link${prefix}_3">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
            	<geometry>
                    <sphere radius="${link2_radius}"/>
            	</geometry>
            	<material name="green" />
            </visual>
    	</link>
    </xacro:macro>

    <xacro:macro name="arm">
	<joint name="arm_joint1_1" type="continuous">
            <origin xyz="0 0 ${base_length/2+link_1_length/2}" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="arm_link1_1"/>
            <axis xyz="0 0 1"/>
        </joint>

	<link name="arm_link1_1">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
            	<geometry>
                    <cylinder length="${link_1_length}" radius="${link_1_radius}"/>
            	</geometry>
            	<material name="green" />
            </visual>
    	</link>

	<joint name="arm_joint1_2" type="fixed">
            <origin xyz="0 0 ${link_1_length/2}" rpy="0 0 0"/>
            <parent link="arm_link1_1"/>
            <child link="arm_link1_3"/>
        </joint>
	
	<link name="arm_link1_3">
            <visual>
                <origin xyz=" 0 0 0" rpy="0 0 0" />
            	<geometry>
                    <sphere radius="${link_1_radius}"/>
            	</geometry>
            	<material name="green" />
            </visual>
    	</link>
        
	<arm_link prefix="2" link1_length="${link_1_length}" link1_radius="${link_1_radius}" link2_length="${link_2_length}" link2_radius="${link_2_radius}"/>
	<arm_link prefix="3" link1_length="${link_2_length}" link1_radius="${link_2_radius}" link2_length="${link_3_length}" link2_radius="${link_3_radius}"/>

    </xacro:macro>
   
</robot>
